### ISSUE TITLE
Mnemonic storage issue with Taki

### ISSUE THREAD

**Issue by ajun-rlynetwork** [rally-dfs/rly-network-mobile-sdk#77]
https://rlynetworkassociation.slack.com/archives/C05750N6Q58/p1686153419139219

_interesting, so looks like the account is getting wiped when you uninstall the expo app, the RN app is looking for it, returning something but it’s not a valid pk, going to add my colleague_

**Comment by rweald** [comment]
There was an additional report that can be found here - https://rlynetworkassociation.slack.com/archives/C05750N6Q58/p1687189293302029

and a discussion about replication of the issue that started here - https://rlynetworkassociation.slack.com/archives/C03UT3S83JL/p1687200057858269
